### ISSUE TITLE
Add IsMineral and IsGeyser filters

### ISSUE THREAD

**Issue by alkurbatov** [alkurbatov/cpp-sc2#24]
Searching of resources 'units' is one of the most often tasks executed by bot developers thus we should provide a filter for it.

**Comment by mboedigh** [comment]
If we want to know whether a unit is a mineral (or vespene), we can either check the field mineral_content > 0, or we can check the unit type against the list of all mineral field types. Checking the type is more foolproof, but more involved and can change over time. It is more foolproof because at the beginning of the game, the mineral contents of snapshot units (those out of immediate vision range) don't report mineral contents (i.e. it is set to 0). 

I propose using the switch approach.

what file should this go into, or should it be a new file such as sc2_unit_filters.h?

**Comment by alkurbatov** [comment]
Unfortunately mineral_content is not reliable because snapshots (when minerals hidden under fog) have mineral_content==0. Thus in case of calculations of expansions locations such filter will be unusable.

>what file should this go into, or should it be a new file such as sc2_unit_filters.h?

I plan to add separate file for filters.

**Comment by mboedigh** [comment]
Agreed. Is this something you are already doing? I have versions of IsMineralField, IsVespeneGeyser, and IsTownHall ready for testing, and merging. 
If you are doing it already, then can I ask that we have versions that take UNIT_TYPEID as well as the standard filters taking const Unit &?  The reason is that I don't always have a reference to an Unit when making the comparison (and the whole unit isn't needed anyway).

**Comment by alkurbatov** [comment]
I have two implementations here:
https://github.com/alkurbatov/suvorov-bot/blob/master/src/core/Helpers.cpp#L96

But this is not what is in the list in the nearest time.

**Comment by alkurbatov** [comment]
I think, we should take a look at python-sc2 first as it has similar filters. The filters are used for some time already by wide community of developers.

**Comment by mboedigh** [comment]
After a brief search I couldn't find the filters in pysc2, pysc2-examples, pysc2-replay or pysc2-tutorial, but my python skill is almost non-existent.

The implementations you have seem fine. I have a couple comments
IsTownHall excludes the flying variants. My own preference is that IsTownHall includes all of them and  I can separately look for is_flying if I'm interested in that detail. For example, If my bot want to do economic damage by killing a base, and Terran lifts off, I still want to find it. 

IsGasWorker (although that might be out of scope here), may fail when the workers go subterranean. 

Are you going to split IsFoggyResource into separate calls for minerals and vespene?

What I was asking for before was an interface like this:
```
bool IsFoggyResource::operator()(const sc2::Unit& unit_) const // for filters, unwraps unit_type and calls the next
bool IsFoggyResource::operator()(const UNIT_TYPEID id) const; // does the work, stand alone function, doesn't require an instance of Unit to use it. 

```

**Comment by alkurbatov** [comment]
>IsTownHall excludes the flying variants.

True, this needs to be fixed. My bot doesn't really care now about flying town halls, but the general filter have to.

>IsGasWorker (although that might be out of scope here), may fail when the workers go subterranean.

This is very specific thing related to my bot's implementation. It has several problems and will not be added to the API.


> Are you going to split IsFoggyResource into separate calls for minerals and vespene?

I am not sure that fogged resources filter should be included into the API, need to think about it.

>What I was asking for before was an interface like this:

Could you provide an example of usage of
`bool IsFoggyResource::operator()(const UNIT_TYPEID id) const;` ?

**Comment by mboedigh** [comment]
When I say split `IsFoggyResource` into two, I was imprecise. All I meant was that instead of one function `IsResource`, there would be three: `IsResource`, `IsMineralField`, `IsVespeneyGeyser`. 
We've already discussed "foggy" and I think you and I agree that due to `Unit.DisplayType==Snapshot` issues, we have to rely on `UNIT_TYPEID` to determine whether a unit is a resource, which seems to be exactly what `IsFoggyResource ` does

My use case with `UNIT_TYPEID`  isn't specific to resources. It comes up in several spots, but one common one, is when my bot is planning. At that point there may not be units created, and the bot is working with hypotheticals. It has access to UnitTypeData and therefore to unit_type_id. Looking through my bot, I  use it for planning production to counter hypothetical threats and for planning sim cities, maybe elsewhere. 
I think of the version using UNIT_TYPEID as the "raw" version and version taking Unit const & as a convenience. The raw versions will work with any lambda function a person wants to create. The convenience function makes assumptions. They are natural, and useful assumptions, to be sure, but are slightly limiting. 
That said, I already have my own collection of filters, which I can continue to use. It is just something to consider.

**Comment by alkurbatov** [comment]
Done.
