### ISSUE TITLE
Support BuildingUnderAttack and UnitUnderAttack alerts

### ISSUE THREAD

**Issue by alkurbatov** [alkurbatov/cpp-sc2#7]
Quite useful alerts to identify whether a unit/building is under attack.

Additional details:
https://github.com/Blizzard/s2client-proto/blob/d3d18392f9d7c646067d447df0c936a8ca57d587/s2clientprotocol/sc2api.proto#L687

**Comment by yanntm** [comment]
hi these other events could be useful and serve as a template for adding more events :
https://github.com/yanntm/s2client-api/commit/7bee876cc8f1ac9c272327c610014f1b1b1f907f
https://github.com/yanntm/s2client-api/commit/842559416846cb79b87214bab649a70d1398a3db

I'd like to merge them into your code since I'm now using it as basis.

**Comment by alkurbatov** [comment]
Now we have the `OnUnitDamaged` event so there is no need in additional alerts.
